#!/bin/bash

# define the current image to be used by script
DOCKERIMAGE="nano_assembly"

set -eo pipefail

help() {
echo -e "Run Read Assembly with SPAdes\n\n
 Usage:\n\n

 ./run [FASTQ Directory] [Reference Genome filepath] [Reference Genome Genes filepath] [Output directory] [Additional Flags]\n\n

 If NOT supplying reference genome and/or reference genes, enter 'NA'

 All FASTQ pairs within the directory will be processed independently\n
 \n"
}

function check_paths() {
 # Get absolute result paths for mounting
 # Note that the directory containing a file is gathered (if applicable)
 QUERY=$(realpath ${1%/*})
 REFGENOME_DIR=$(realpath ${2%/*})
 RESULT=$(realpath ${3%/*})

 # Check directories - query must exist or error out
 if ! [[ -d $QUERY ]]; then 
 echo -e "\nThe directory containing query ${QUERY} doesn\'t exist. 
         Please check the path provided and re-run the script."; 
 exit 1;
 fi
 if ! [[ -d $REFGENOME_DIR ]]; then 
 echo -e "\nThe directory containing reference genomes ${REFGENOME_DIR} doesn\'t exist. 
         Please check the path provided and re-run the script."; 
 exit 1;
 fi

 # Results directory can be created if it doesn't exist 
 if ! [[ -d $RESULT ]]; then
  # redirect to stderr so function only returns prinft output 
  echo -e "\nCreating output directory: ${RESULT}\n" >&2 
  mkdir -p "${RESULT}"
 fi

 # return the mount path
 printf " -v %s:/queries/ -v %s:/refgenomes/ -v %s:/results/" "$QUERY" $REFGENOME_DIR "$RESULT";
}

function check_input_to_list() {
  ALLOWED_COMMANDS=$1
  INPUT="$2"
  echo $ALLOWED_COMMANDS | tr " " '\n' | grep -F -q -x "$INPUT"
}

# If incorrect number of arguments given, throw help and exit
if [[ $# -lt 4 ]]; then help && exit 0; fi

FASTQ_DIR=$1
REFGENOME_LOC=$2
REFGENES_LOC=$3
OUT_DIR=$4
ALL_OTHER_INPUT=${@:4}

# Get paths for mounting
MOUNTPATHS=$(check_paths $FASTQ_DIR $REFGENOME_LOC $OUT_DIR)

docker run --rm $MOUNTPATHS -u $(id -u):$(id -g) $DOCKERIMAGE /scripts/main.py $REFGENOME_LOC $REFGENES_LOC $ALL_OTHER_INPUT
